# Generated by Django 2.2.6 on 2021-06-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
