# Generated by Django 2.2.6 on 2021-06-12 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('full time', 'Игра'), ('first half', 'Первый тайм'), ('second half', 'Второй тайм')], default='full time', max_length=32, verbose_name='Тип')),
                ('score_home', models.IntegerField(default=0, verbose_name='Домашняя команда')),
                ('score_away', models.IntegerField(default=0, verbose_name='Выездная команда')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_forecast', to='tournaments.Match', verbose_name='Матч')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_forecast', to='tournaments.Tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_forecast', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
                'db_table': 'forecast',
            },
        ),
    ]
