# Generated by Django 2.2.6 on 2021-06-18 06:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0003_forecast'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('forecast_type', 'match', 'tournament', 'user')},
        ),
    ]
