# Generated by Django 2.2.6 on 2021-06-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20210618_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageCoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.IntegerField(default=1, verbose_name='Коэффициент')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_stage_coef', to='tournaments.Stage', verbose_name='Стадия')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_stage_coef', to='tournaments.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Коэффициент на стадии',
                'verbose_name_plural': 'Коэффициенты на стадии',
                'db_table': 'stage_coefficient',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('exact result', 'Точный результат матча'), ('goals difference', 'Разница голов (кроме ничейного исхода)'), ('match result', 'Исход матча (в том числе ничейный исход)'), ('champion', 'Победитель турнира')], default='match result', max_length=32, verbose_name='Правило')),
                ('points', models.IntegerField(default=1, verbose_name='Очки')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_rules', to='tournaments.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Правило',
                'verbose_name_plural': 'Правила',
                'db_table': 'rule',
            },
        ),
    ]
