# Generated by Django 2.2.6 on 2021-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_rule_stagecoefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='stagecoefficient',
            name='coefficient',
            field=models.FloatField(default=1.0, verbose_name='Коэффициент'),
        ),
    ]
