# Generated by Django 2.2.6 on 2021-06-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20210618_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='code',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='open',
            field=models.BooleanField(default=False, verbose_name='Открытый'),
        ),
    ]
