# Generated by Django 2.2.6 on 2024-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20210623_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='checkin',
            field=models.BooleanField(default=False, verbose_name='Зачекинился'),
        ),
    ]
