# Generated by Django 2.2.6 on 2024-06-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_participant_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
