# Generated by Django 2.2.6 on 2026-06-09 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0010_participant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastwinner',
            name='winner_type',
            field=models.CharField(choices=[('first', 'Первый'), ('second', 'Второй'), ('third', 'Третий')], default='first', max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('exact result', 'Точный результат матча'), ('goals difference', 'Разница голов (кроме ничейного исхода)'), ('match result', 'Исход матча (в том числе ничейный исход)'), ('winner1', 'Победитель турнира 1'), ('winner2', 'Победитель турнира 2'), ('winner3', 'Победитель турнира 3')], default='match result', max_length=32, verbose_name='Правило'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastwinner',
            unique_together={('tournament', 'team', 'user', 'winner_type')},
        ),
    ]
