# Generated by Django 2.2.6 on 2021-06-16 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('sent_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Дата отправки')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'db_table': 'mail',
            },
        ),
    ]
